// Acá tenemos el modulo para Paises y capitales
export const paisesCapitales = {
    "Argentina": "Buenos Aires",
    "Brasil": "Brasilia",
    "Chile": "Santiago",
    "Colombia": "Bogotá",
    "México": "Ciudad de México",
    "Perú": "Lima",
    "Estados Unidos": "Washington D.C.",
    "Canadá": "Ottawa",
    "España": "Madrid",
    "Francia": "París",
    "Alemania": "Berlín",
    "Italia": "Roma",
    "Reino Unido": "Londres",
    "Japón": "Tokio",
    "China": "Pekín",
    "India": "Nueva Delhi",
    "Australia": "Canberra",
    "Nueva Zelanda": "Wellington",
    "Sudáfrica": "Pretoria",
    "Egipto": "El Cairo",
    "Rusia": "Moscú",
    "Corea del Sur": "Seúl",
    "Turquía": "Ankara",
    "Grecia": "Atenas",
    "Portugal": "Lisboa",
    "Suecia": "Estocolmo",
    "Noruega": "Oslo",
    "Dinamarca": "Copenhague",
    "Finlandia": "Helsinki",
    "Polonia": "Varsovia"
};